#!/bin/bash
set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

DEV_DIR="$HOME/Development"

echo -e "${GREEN}Cloning repositories to $DEV_DIR...${NC}\n"

clone_repo() {
    local category="$1"
    local url="$2"
    local name=$(basename "$url" .git)
    local target="$DEV_DIR/$category/$name"

    if [ -d "$target" ]; then
        echo -e "${YELLOW}→${NC} Already exists: $category/$name"
    else
        mkdir -p "$DEV_DIR/$category"
        echo -e "${GREEN}+${NC} Cloning $category/$name..."
        git clone "$url" "$target" 2>/dev/null || echo -e "${RED}✗${NC} Failed: $url"
    fi
}

clone_repo "Dfinitiv" "git@github.com:dfinitiv/.github.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/admin-dashboard.git"
clone_repo "Dfinitiv" "git@github.com:BrianVia/claude-containers.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/constructs.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/demo-ios"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/deployment-manager.git"
clone_repo "Dfinitiv" "git@github.com:BrianVia/linear-triage.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/mojo-ads.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/mojo-browser-extension.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/mojo-offers.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/mojo-plaid.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/mojo-users"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/pegasus.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/retailmenot-scraper.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-aasa.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-admin.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-analytics.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-arch.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-bff.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-bot.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-brext.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-cartera.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-chat.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-components.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-coupons.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-demo.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-geo.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-guides.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-ios.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-links.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-media.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-metadata.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-offers.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-personalize.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-rewards-network.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-sockets.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-studio.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-tango.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvy-webhooks.git"
# Repos merged from ansible/tasks/dfinitiv-projects.yml
clone_repo "Dfinitiv" "git@github.com:adzerk/adzerk-decision-sdk-js.git"
clone_repo "Dfinitiv" "git@github.com:BrianVia/brian-bot.git"
clone_repo "Dfinitiv" "git@github.com:BrianVia/dfinitiv-website.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/mojo-browser-extension-instructions.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/mojo-ios.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/mojo-marketing.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/pegasus-ios.git"
clone_repo "Dfinitiv" "git@github.com:BrianVia/savvy-publisher.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/SavvyKit.git"
clone_repo "Dfinitiv" "git@github.com:dfinitiv/savvyspendsmart-guide.git"

clone_repo "MCP-Servers" "git@github.com:Alec2435/amazon-fresh-server.git"
clone_repo "MCP-Servers" "git@github.com:serkanh/cloudwatch-logs-mcp.git"
clone_repo "Open-Source" "git@github.com:anthropics/anthropic-cookbook.git"
clone_repo "Open-Source" "git@github.com:satnaing/astro-paper.git"
clone_repo "Open-Source" "git@github.com:steipete/bird.git"
clone_repo "Open-Source" "git@github.com:FujiwaraChoki/MoneyPrinterV2.git"
clone_repo "Open-Source" "git@github.com:redotvideo/examples.git"
clone_repo "Open-Source" "git@github.com:sst/sst.git"
clone_repo "Open-Source" "git@github.com:BrianVia/storm.git"
clone_repo "Open-Source" "git@github.com:gorhill/uBlock.git"
clone_repo "Open-Source" "git@github.com:BrianVia/desktop.git"
clone_repo "Personal" "https://github.com/BrianVia/amazon-library-search-extension.git"
clone_repo "Personal" "git@github.com:BrianVia/amazon-order-exporter.git"
clone_repo "Personal" "git@github.com:BrianVia/ansible.git"
clone_repo "Personal" "git@github.com:BrianVia/article-print-extension.git"
clone_repo "Personal" "git@github.com:satnaing/astro-paper.git"
clone_repo "Personal" "https://github.com/BrianVia/audio-to-ideas-generator.git"
clone_repo "Personal" "git@github.com:Significant-Gravitas/AutoGPT.git"
clone_repo "Personal" "git@github.com:BrianVia/automated-web-agency.git"
clone_repo "Personal" "git@github.com:dfinitiv/aws-accounts-labeler-extension.git"
clone_repo "Personal" "https://github.com/BrianVia/aws-constructs.git"
clone_repo "Personal" "git@github.com:BrianVia/banana-image-gen.git"
clone_repo "Personal" "git@github.com:BrianVia/blog.git"
clone_repo "Personal" "git@github.com:BrianVia/book-library.git"
clone_repo "Personal" "git@github.com:BrianVia/chrome-high-mem-usage.git"
clone_repo "Personal" "git@github.com:T3-Content/claude-blocker.git"
clone_repo "Personal" "git@github.com:BrianVia/claude-pod-extension.git"
clone_repo "Personal" "https://github.com/BrianVia/cloudflare-workers-api-template.git"
clone_repo "Personal" "https://github.com/BrianVia/compound-interest-calculator.git"
clone_repo "Personal" "git@github.com:BrianVia/computer-repair-near-me.git"
clone_repo "Personal" "https://github.com/BrianVia/custom-rss-feeds.git"
clone_repo "Personal" "git@github.com:BrianVia/docs.git"
clone_repo "Personal" "https://github.com/tarikpnr/react-native-typescript-starter.git"
clone_repo "Personal" "git@github.com:BrianVia/image-to-data-website.git"
clone_repo "Personal" "git@github.com:BrianVia/dotfiles.git"
clone_repo "Personal" "https://github.com/BrianVia/duck-generator.git"
clone_repo "Personal" "git@github.com:BrianVia/dynomite.git"
clone_repo "Personal" "git@github.com:BrianVia/gif-video-chrome-extension.git"
clone_repo "Personal" "git@github.com:BrianVia/github-home-page.git"
clone_repo "Personal" "https://github.com/BrianVia/hacker-news-favorite-books.git"
clone_repo "Personal" "git@github.com:BrianVia/home-dashboard.git"
clone_repo "Personal" "git@github.com:BrianVia/image-model-cost-calculator.git"
clone_repo "Personal" "https://github.com/BrianVia/inklink-vibe-edit.git"
clone_repo "Personal" "git@github.com:BrianVia/kaletube-extension.git"
clone_repo "Personal" "https://github.com/BrianVia/lazy-web-dev.git"
clone_repo "Personal" "https://github.com/BrianVia/live-knowledge-base.git"
clone_repo "Personal" "git@github.com:BrianVia/mam-api-client.git"
clone_repo "Personal" "git@github.com:BrianVia/maptoposter.git"
clone_repo "Personal" "git@github.com:BrianVia/media-uploader.git"
clone_repo "Personal" "git@github.com:BrianVia/memes-platform.git"
clone_repo "Personal" "git@github.com:BrianVia/notes.git"
clone_repo "Personal" "git@github.com:BrianVia/nyt-cooking-parser.git"
clone_repo "Personal" "git@github.com:BrianVia/OG-scraper.git"
clone_repo "Personal" "git@github.com:BrianVia/online-pinball.git"
clone_repo "Personal" "git@github.com:BrianVia/parrot.git"
clone_repo "Personal" "https://github.com/BrianVia/portfolio-landing-page.git"
clone_repo "Personal" "git@github.com:BrianVia/projects.git"
clone_repo "Personal" "https://github.com/BrianVia/ramsay.git"
clone_repo "Personal" "git@github.com:BrianVia/room-repainter.git"
clone_repo "Personal" "git@github.com:BrianVia/scrollback.git"
clone_repo "Personal" "git@github.com:BrianVia/shortform-summaries.git"
clone_repo "Personal" "git@github.com:BrianVia/slackpipes.git"
clone_repo "Personal" "git@github.com:BrianVia/sourcemap-loader-extension.git"
clone_repo "Personal" "git@github.com:alula/SpaceCadetPinball.git"
clone_repo "Personal" "https://github.com/BrianVia/sweatshop.git"
clone_repo "Personal" "git@github.com:BrianVia/torrent-uploader-extension.git"
clone_repo "Personal" "git@github.com:brianvia/torrent-uploader"
clone_repo "Personal" "git@github.com:BrianVia/transcriptor.git"
clone_repo "Personal" "git@github.com:BrianVia/velocity-design-v1.git"
clone_repo "Personal" "git@github.com:BrianVia/video-clip-creator.git"
clone_repo "Personal" "git@github.com:BrianVia/VoiceInk.git"
clone_repo "Personal" "git@github.com:BrianVia/workspace.git"

# Repos merged from ansible/tasks/personal-projects.yml
clone_repo "Personal" "git@github.com:StephanAkkerman/bitcoin-rainbow-chart.git"
clone_repo "Personal" "https://github.com/BrianVia/dinner-club.git"
clone_repo "Personal" "git@github.com:froggerit/froggerdb.git"

echo -e "
${GREEN}Done! All repos cloned.${NC}"
